spring:
  datasource:
    url: jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=staj_proje;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
    username: dilaykal
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      # Dikkat: Bu ayar sadece geliştirme ortamı için önerilir.
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml